let students = {
    arakel: {
        syntax: 3,
        vars: 3,
        naming: 3,
        numbers: 3,
        strings: 2.5,
        boolean: 3,
        null: 3,
        undefined: 3,
        operators: 3,
        math: 3,
        conditionals: 2.5,
        loops: 2.5,
        arrays: 3,
        objects: 0,
        error: 0,
        functions: 2,
        modules: 0,
        classes: 0,
        prototypes: 0,
        inheritance: 0,
        descriptors: 0,
        asyncLoop: 0,
        promise: 2,
        asyncAwait: 2,
        generators: 0,
    },
    tyush: {
        syntax: 2,
        vars: 2.5,
        naming: 2.5,
        numbers: 3,
        strings: 2,
        boolean: 3,
        null: 3,
        undefined: 3,
        operators: 2.5,
        math: 1.5,
        conditionals: 2.5,
        loops: 2.5,
        arrays: 1.5,
        objects: 0,
        error: 1.5,
        functions: 1.5,
        modules: 0,
        classes: 0,
        prototypes: 0,
        inheritance: 0,
        descriptors: 0,
        asyncLoop: 0,
        promise: 2.5,
        asyncAwait: 2.5,
        generators: 0,
    },
    edgar: {
        syntax: 3,
        vars: 3,
        naming: 3,
        numbers: 3,
        strings: 3,
        boolean: 3,
        null: 3,
        undefined: 3,
        operators: 3,
        math: 3,
        conditionals: 3,
        loops: 3,
        arrays: 3,
        objects: 1,
        error: 3,
        functions: 3,
        modules: 1,
        classes: 0,
        prototypes: 1,
        inheritance: 0,
        descriptors: 0,
        asyncLoop: 0,
        promise: 2,
        asyncAwait: 2,
        generators: 0,
    },
    emily: {
        syntax: 3,
        vars: 3,
        naming: 3,
        numbers: 3,
        strings: 3,
        boolean: 3,
        null: 3,
        undefined: 3,
        operators: 3,
        math: 3,
        conditionals: 3,
        loops: 3,
        arrays: 3,
        objects: 0,
        error: 0,
        functions: 3,
        modules: 1,
        classes: 0,
        prototypes: 1,
        inheritance: 1,
        descriptors: 0,
        asyncLoop: 0,
        promise: 3,
        asyncAwait: 3,
        generators: 0,
    },
    hayk: {
        syntax: 2.5,
        vars: 3,
        naming: 3,
        numbers: 2.5,
        strings: 2.5,
        boolean: 3,
        null: 2,
        undefined: 2,
        operators: 2.5,
        math: 2.5,
        conditionals: 2.5,
        loops: 2,
        arrays: 2.5,
        objects: 1,
        error: 1,
        functions: 2,
        modules: 1,
        classes: 0,
        prototypes: 1,
        inheritance: 1,
        descriptors: 0,
        asyncLoop: 0,
        promise: 2.5,
        asyncAwait: 2.5,
        generators: 0,
    },
    artur: {
        syntax: 3,
        vars: 3,
        naming: 3,
        numbers: 3,
        strings: 3,
        boolean: 3,
        null: 2,
        undefined: 3,
        operators: 3,
        math: 3,
        conditionals: 3,
        loops: 2,
        arrays: 3,
        objects: 1,
        error: 1,
        functions: 2,
        modules: 1,
        classes: 0,
        prototypes: 1,
        inheritance: 1,
        descriptors: 0,
        asyncLoop: 0,
        promise: 1,
        asyncAwait: 1,
        generators: 0,
    },
}

let arr = [{...students}]

for (let i = 0; i < arr.length; i++) {
    // console.log(arr[i],'i');
    let a = Object.keys(arr[i])
    let b = Object.values(arr[i])
    // console.log(a,'a');
    for (let j = 0; j < a.length; j++) {
        // console.log(b[j], 'v');
        // console.log(Object.keys(b[j]),'value');
        //        console.log(b[j].syntax);
        // if (a[j])
    }
}


